# Generated by Django 5.0.4 on 2024-04-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productreview",
            options={
                "ordering": ["-created_on"],
                "verbose_name_plural": "Product Reviews",
            },
        ),
        migrations.RenameField(
            model_name="productreview",
            old_name="review",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="productreview",
            old_name="date",
            new_name="created_on",
        ),
        migrations.AlterField(
            model_name="productreview",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Star"),
                    (2, "2 Stars"),
                    (3, "3 Stars"),
                    (4, "4 Stars"),
                    (5, "5 Stars"),
                ],
                default=5,
            ),
        ),
    ]
