# Generated by Django 5.0.4 on 2024-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_newsletter_newslettersubscriber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
