# Generated by Django 5.0.4 on 2024-04-21 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="user",
        ),
    ]
