# Generated by Django 5.0.4 on 2024-05-03 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "Categories"},
        ),
    ]
