# Generated by Django 5.0.4 on 2024-05-04 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0008_alter_category_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Newsletter",
        ),
        migrations.DeleteModel(
            name="NewsletterSubscriber",
        ),
    ]
