# Generated by Django 5.0.4 on 2024-04-20 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userextend", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserHistory",
        ),
    ]
